#!/usr/bin/env bash
# Configure your domain zone so that the
# +subdomain www points to your load-balancer IP

print_info () {
	script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 2 ]; then
	print_info "$1" "$2"
else
	subdomains=("www" "lb-01" "web-01" "web-02")
	for subdomain in "${subdomains[@]}"; do
		print_info "$1" "$subdomain"
	done
fi
