#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt-get update
sudo apt-get install nginx -y
systemctl start nginx
sudo ufw allow 'nginx HTTP'
sudo chown -R $USER:$USER /var/www/html
sudo chown -R $USER:$USER /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
systemctl restart nginx
