#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
systemctl start nginx
